@startuml

!include ../../PointCloudMap/PointCloudMap_Class.puml

class PointCloudMapBS{
    + PointCloudMapBS()
    + ~PointCloudMapBS()
    + virtual void addPose(const Pose2D &p)
    + virtual void addPoints(const std::vector<LPoint2D> &lps)
    + virtual void makeGlobalMap()
    + virtual void makeLocalMap()
    + virtual void remakeMaps(const std::vector<Pose2D> &newPoses)
}

PointCloudMapBS --|> PointCloudMap

@enduml