@startuml

/'
    set reference scan points to nntab as pointer
    input: const std::vector<LPoint2D> &rlps
'/

(*) --> "nntab.clear()"
--> if "0 <= size_t i < rlps.size()" as judge_i then
        --> [Yes] "nntab.addPoint(&rlps[i])"
        --> judge_i
    else
        -> [No] (*)

@enduml