@startuml

(*) --> "pcmap = &pcmapLP"
--> "RefScanMaker *rsm = &rsmLM
DataAssociator *dass = &dassGT
CostFunction *cfunc = &cfuncPD
PoseOptimizer *popt = &poptSL
LoopDetector *lpd = &lpdSS"
--> "popt->setCostFunction(cfunc)"
--> "poest.setDataAssociator(dass)
poest.setPoseOptimizer(popt)"
--> "pfu.setDataAssociator(dass)"
--> "smat.setPointCloudMap(pcmap)
smat.setRefScanMaker(rsm)"
--> "sfront->setLoopDetector(lpd)
sfront->setPointCloudMap(pcmap)
sfront->setDgCheck(true)"
-->(*)

@enduml