@startuml

skinparam classAttributeIconSize 0

class LoopDetector {
    # PoseGraph *pg
    # std::vector<LoopMatch> loopMatches
    + LoopDetector()
    + ~LoopDetector()
    + std::vector<LoopMatch> &getLoopMatches(){return(loopMatches)}
    + void setPoseGraph(PoseGraph *p){pg = p}
    + virtual bool detectLoop(Scan2D *curScan, Pose2D &curPose, int cnt)
}

LoopDetector <|-- LoopDetectorSS

@enduml