@startuml

!include ../Pose2D/Pose2D_Class.puml
!include ../Scan2D/Scan2D_Class.puml
!include ../PoseGraph/PoseGraph_Class.puml

class LoopInfo <<struct>>{
    bool arcked
    int curId
    int refId
    Pose2D pose
    double score
    Eigen::Matrix3d cov
    LoopInfo() : arcked(false), curId(-1), refId(-1), score(-1)
    ~LoopInfo()
    void setArcked(bool t){arcked = t}
}

class LoopMatch <<struct>>{
    Scan2D curScan
    Scan2D refScan
    LoopInfo info
    LoopMatch()
    LoopMatch(Scan2D &cs, Scan2D &rs, LoopInfo &i){curScan = cs; refScan = rs; info = i}
}

class LoopDetector {
    # PoseGraph *pg
    # std::vector<LoopMatch> loopMatches
    + LoopDetector()
    + ~LoopDetector()
    + std::vector<LoopMatch> &getLoopMatches(){return(loopMatches)}
    + void setPoseGraph(PoseGraph *p){pg = p}
    + virtual bool detectLoop(Scan2D *curScan, Pose2D &curPose, int cnt)
}

LoopDetector o-- PoseGraph
LoopDetector o-- LoopMatch
LoopMatch o-- LoopInfo
LoopMatch o-- Scan2D
LoopInfo o-- Pose2D

@enduml