@startuml

skinparam classAttributeIconSize 0

class PointCloudMap{
    + {static} const int MAX_POINT_NUM = 1000000
    + int nthre
    + std::vector<Pose2D> poses
    + Pose2D lasePose
    + Scan2D lastScan
    + std::vector<LPoint2D> globalMap
    + std::vector<LPoint2D> localMap
    + PointCloudMap() : nthre(1) {globalMap.reserve(MAX_POINT_NUM)}
    + ~PointCloudMap()
    + void setNthre(int n){nthre = n}
    + void setLastPose(const Pose2D &p){lastPose = p}
    + Pose2D getLastPose() {return(lastPose)}
    + void setLastScan(const Scan2 &s){lastScan = s}
    + virtual void addPose(const Pose2D &p) = 0
    + virtual void addPoints(const std::vector<LPoint2D> &lps)
    + virtual void makeGlobalMap() = 0
    + virtual void makeLocalMap() = 0
    + virtual void remakeMaps(const std::vector<Pose2D> &newPoses) = 0
}

PointCloudMap o-- Pose2D
PointCloudMap o-- Scan2D
PointCloudMap o-- LPoint2D

@enduml